### ISSUE TITLE
error while building from source for nvcc(for nvidia)

### ISSUE THREAD

**Issue by mn265** [ROCmSoftwarePlatform/hcFFT#8]
**1)I am getting below error while building hcFFT from source as suggested in installation guide for nvcc path (for nvidia):**
hcfft/lib/src/nvcc_detail/hipfft.cpp:29:43: error: unknown type name 'cufftResult'; did you mean 'hcfftResult'?
hipfftResult hipCUFFTResultToHIPFFTResult(cufftResult cuResult) {
                                          ^~~~~~~~~~~
                                          hcfftResult
hcfft/lib/src/../include/hcc_detail/../hcfft.h:88:3: note: 'hcfftResult' declared here
} hcfftResult;
  ^
hcfft/lib/src/nvcc_detail/hipfft.cpp:31:10: error: use of undeclared identifier 'CUFFT_SUCCESS'; did you mean
      'HCFFT_SUCCESS'?
    case CUFFT_SUCCESS:
         ^~~~~~~~~~~~~
         HCFFT_SUCCESS
hcfft/lib/src/../include/hcc_detail/../hcfft.h:72:3: note: 'HCFFT_SUCCESS' declared here
  HCFFT_SUCCESS = 0,         //  The hcFFT operation was successful
  ^

hcfft/lib/src/nvcc_detail/hipfft.cpp:33:10: error: use of undeclared identifier 'CUFFT_INVALID_PLAN'; did you mean
      'HCFFT_INVALID_PLAN'?
    case CUFFT_INVALID_PLAN:
         ^~~~~~~~~~~~~~~~~~
         HCFFT_INVALID_PLAN
hcfft/lib/src/../include/hcc_detail/../hcfft.h:73:3: note: 'HCFFT_INVALID_PLAN' declared here
  HCFFT_INVALID_PLAN = 1,    //  hcFFT was passed an invalid plan handle
  ^

**2) similar to hiprand , hipblas  when hipFFT marshalling library will be aviailable??**

**Comment by dagamayank** [comment]
@mn265 `hcFFT` has been deprecated and has been replaced by the more optimized and mature [`rocFFT`](https://github.com/ROCmSoftwarePlatform/rocFFT) library.

**Comment by mn265** [comment]
@dagamayank  rocFFT support for fft functionalities(hipfft) to run on both Nvidia and AMD as hiprand and hipblas marshaling library??
